version: '3.8'

services:
  discord-bot:
    image: .
    container_name: discord-bot
    environment:
      - DISCORD_TOKEN=your_discord_token_here
      - MONGO_URI=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    restart: always

volumes:
  mongo-data:
