version: '3.8'

services:
  wattson:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wattson
    environment:
      - NODE_ENV=production
      - ENV=docker
      - MONGO_URI=mongodb://root:example@mongo:27017/wattsondb?authSource=admin
    volumes:
      - ./logs:/home/bun/app/logs
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wattsondb
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
volumes:
  mongo-data:
