// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  GENERAL: {
    /**
     * W​a​t​t​s​o​n​,​ ​i​n​ ​s​e​r​v​i​c​e​ ​f​o​r​ ​E​u​r​o​p​e
     */
    EMBED_FOOTER_TEXT: string;
  };
  UTIL: {
    PING: {
      /**
       * W​a​t​t​s​o​n​ ​-​ ​C​o​n​s​t​a​b​l​e​ ​P​o​n​g
       */
      RESPONSE_TITLE: string;
      /**
       * A​h​!​ ​A​ ​s​i​g​n​a​l​ ​m​o​s​t​ ​c​u​r​i​o​u​s​ ​—​ ​I​ ​d​a​r​e​s​a​y​,​ ​t​h​e​ ​l​a​t​e​n​c​y​ ​i​s​ ​b​u​t​ ​a​ ​f​l​e​e​t​i​n​g​ ​w​h​i​s​p​e​r​.​.
       */
      RESPONSE_DESCRIPTION: string;
      /**
       * S​e​r​v​i​c​e​ ​L​a​t​e​n​c​y
       */
      RESPONSE_FIELD_SERVICE_LATENCY: string;
      /**
       * S​e​r​v​i​c​e​ ​U​p​t​i​m​e
       */
      RESPONSE_FIELD_SERVICE_UPTIME: string;
      /**
       * A​P​I​ ​L​a​t​e​n​c​y
       */
      RESPONSE_FIELD_API_LATENCY: string;
    };
  };
};

export type TranslationFunctions = {
  GENERAL: {
    /**
     * Wattson, in service for Europe
     */
    EMBED_FOOTER_TEXT: () => LocalizedString;
  };
  UTIL: {
    PING: {
      /**
       * Wattson - Constable Pong
       */
      RESPONSE_TITLE: () => LocalizedString;
      /**
       * Ah! A signal most curious — I daresay, the latency is but a fleeting whisper..
       */
      RESPONSE_DESCRIPTION: () => LocalizedString;
      /**
       * Service Latency
       */
      RESPONSE_FIELD_SERVICE_LATENCY: () => LocalizedString;
      /**
       * Service Uptime
       */
      RESPONSE_FIELD_SERVICE_UPTIME: () => LocalizedString;
      /**
       * API Latency
       */
      RESPONSE_FIELD_API_LATENCY: () => LocalizedString;
    };
  };
};

export type Formatters = {};
